import { HomeAssistant } from '../src/models/hass';

export const hass = {
	states: {
		'light.lounge': {
			entity_id: 'light.lounge',
			state: 'on',
			attributes: {
				min_color_temp_kelvin: 2695,
				max_color_temp_kelvin: 6535,
				min_mireds: 153,
				max_mireds: 371,
				supported_color_modes: ['color_temp', 'rgb'],
				color_mode: 'color_temp',
				brightness: 155,
				color_temp_kelvin: 2695,
				color_temp: 371,
				hs_color: [28.406, 65.883],
				rgb_color: [255, 166, 86],
				xy_color: [0.527, 0.388],
				entity_id: ['light.ceiling_bulb_1', 'light.ceiling_bulb_2'],
				icon: 'mdi:ceiling-light',
				friendly_name: 'Lounge Ceiling',
				supported_features: 0,
			},
		},
		'light.ceiling_bulb_1': {
			entity_id: 'light.ceiling_bulb_1',
			state: 'off',
			attributes: {
				min_color_temp_kelvin: 2700,
				max_color_temp_kelvin: 6500,
				min_mireds: 153,
				max_mireds: 370,
				supported_color_modes: ['color_temp', 'rgb'],
				color_mode: null,
				brightness: null,
				color_temp_kelvin: null,
				color_temp: null,
				hs_color: null,
				rgb_color: null,
				xy_color: null,
				togglex_auto: true,
				icon: 'mdi:lightbulb',
				friendly_name: 'Ceiling Light 1',
				supported_features: 32,
			},
			context: {
				parent_id: null,
			},
			last_changed: '2024-09-19T23:45:53.682Z',
			last_updated: '2024-09-19T23:45:53.682Z',
		},
		'light.ceiling_bulb_2': {
			entity_id: 'light.ceiling_bulb_2',
			state: 'off',
			attributes: {
				min_color_temp_kelvin: 2700,
				max_color_temp_kelvin: 6500,
				min_mireds: 153,
				max_mireds: 370,
				supported_color_modes: ['color_temp', 'rgb'],
				color_mode: null,
				brightness: null,
				color_temp_kelvin: null,
				color_temp: null,
				hs_color: null,
				rgb_color: null,
				xy_color: null,
				togglex_auto: true,
				icon: 'mdi:lightbulb',
				friendly_name: 'Ceiling Light 2',
				supported_features: 32,
			},
			context: {
				parent_id: null,
			},
			last_changed: '2024-09-19T23:45:54.052Z',
			last_updated: '2024-09-19T23:45:54.052Z',
		},
		'input_number.volume': {
			entity_id: 'input_number.volume',
			state: 0.4,
			attributes: {
				initial: null,
				editable: true,
				min: 0,
				max: 1,
				step: 0.01,
				mode: 'slider',
				icon: 'mdi:numeric',
				friendly_name: 'Volume Slider',
				unit_of_measurement: '%',
			},
		},
		'zone.home': {
			entity_id: 'zone.home',
			attributes: {
				latitude: 37.27073,
				longitude: -115.801193,
				persons: ['person.jane_doe'],
			},
		},
		'zone.danger': {
			entity_id: 'zone.danger',
			attributes: {
				latitude: -25.715955,
				longitude: -10.415194,
				persons: ['person.jane_doe'],
			},
		},
		'person.john_doe': {
			entity_id: 'person.john_doe',
			attributes: {
				latitude: 46.006823,
				longitude: -105.586907,
			},
		},
		'person.jane_doe': {
			entity_id: 'person.jane_doe',
			attributes: {
				latitude: 56.006823,
				longitude: -115.586907,
			},
		},
		'device_tracker.ark_of_the_covenent': {
			entity_id: 'device_tracker.ark_of_the_covenent',
			attributes: {
				latitude: 28.989944,
				longitude: 29.26883,
			},
		},
		'device_tracker.null_island': {
			entity_id: 'device_tracker.null_island',
			attributes: {
				latitude: 0,
				longitude: 0,
			},
		},
	},
	entities: {
		'light.driveway_light_1': {
			entity_id: 'light.driveway_light_1',
			device_id: '1c81fa4a8d5d3bbc8a9fcf3b9b88b178',
			labels: [],
			platform: 'meross_lan',
			hidden: true,
		},
		'sensor.driveway_light_1_signal_strength': {
			entity_id: 'sensor.driveway_light_1_signal_strength',
			device_id: '1c81fa4a8d5d3bbc8a9fcf3b9b88b178',
			labels: [],
			platform: 'meross_lan',
			entity_category: 'diagnostic',
		},
		'light.driveway_light_2': {
			entity_id: 'light.driveway_light_2',
			device_id: 'e4831420557f6df04603fb0850e7850b',
			labels: [],
			platform: 'meross_lan',
			hidden: true,
		},
		'light.driveway_lamps': {
			entity_id: 'light.driveway_lamps',
			area_id: 'front_yard',
			labels: ['lighting'],
			platform: 'group',
			icon: 'mdi:outdoor-lamp',
		},
		'input_number.volume': {
			entity_id: 'input_number.volume',
			area_id: 'lounge',
			labels: ['lounge_ceiling_fan'],
			platform: 'input_number',
			display_precision: 2,
		},
		'remote.bedroom': {
			entity_id: 'remote.bedroom',
			device_id: '06c14f4b7dd701890e596ebbe354aa97',
			labels: [],
			platform: 'broadlink',
		},
	},
	devices: {
		'08d6a7f58fc934fba97d2ec2a66e7bba': {
			area_id: 'kitchen',
			configuration_url: null,
			created_at: 0,
			disabled_by: null,
			entry_type: null,
			hw_version: '2.0.0',
			id: '08d6a7f58fc934fba97d2ec2a66e7bba',
			labels: [],
			manufacturer: 'Meross',
			model: 'msl120d 2.0.0',
			model_id: null,
			modified_at: 1725659996.044056,
			name_by_user: 'Bar Light 1',
			name: 'Bar Light 1',
			serial_number: null,
			sw_version: '2.1.4',
			via_device_id: null,
		},
		'06c14f4b7dd701890e596ebbe354aa97': {
			area_id: 'bedroom',
			configuration_url: null,
			config_entries: ['792e847ea882139f4e940941fe51417e'],
			created_at: 0,
			disabled_by: null,
			entry_type: null,
			hw_version: null,
			id: '06c14f4b7dd701890e596ebbe354aa97',
			identifiers: [['broadlink', 'a043b0708858']],
			labels: ['ir'],
			manufacturer: 'Broadlink',
			model: 'RM4 mini',
			model_id: null,
			modified_at: 0,
			name_by_user: 'Bedroom Remote',
			name: 'Bedroom Remote',
			primary_config_entry: '792e847ea882139f4e940941fe51417e',
			serial_number: null,
			sw_version: 52079,
			via_device_id: null,
		},
		'1c81fa4a8d5d3bbc8a9fcf3b9b88b178': {
			area_id: 'front_yard',
			configuration_url: null,
			config_entries: ['93277d23619a17d4e4e55ca7a7e3190f'],
			created_at: 0,
			disabled_by: null,
			entry_type: null,
			hw_version: '3.0.0',
			id: '1c81fa4a8d5d3bbc8a9fcf3b9b88b178',
			identifiers: [['meross_lan', '2204113366714352050148e1e98ef959']],
			labels: [],
			manufacturer: 'Meross',
			model: 'msl120d 3.0.0',
			model_id: null,
			modified_at: 1725659995.974389,
			name_by_user: 'Driveway Light 1',
			name: 'Driveway Light 1',
			primary_config_entry: '93277d23619a17d4e4e55ca7a7e3190f',
			serial_number: null,
			sw_version: '3.2.3',
			via_device_id: null,
		},
		e4831420557f6df04603fb0850e7850b: {
			area_id: 'front_yard',
			configuration_url: null,
			config_entries: ['fbe6da823c94a9a04623c4d683b00167'],
			created_at: 0,
			disabled_by: null,
			entry_type: null,
			hw_version: '3.0.0',
			id: 'e4831420557f6df04603fb0850e7850b',
			identifiers: [['meross_lan', '2204119681230052050148e1e98f0afa']],
			labels: [],
			manufacturer: 'Meross',
			model: 'msl120d 3.0.0',
			model_id: null,
			modified_at: 1725659995.951973,
			name_by_user: 'Driveway Light 2',
			name: 'Driveway Light 2',
			primary_config_entry: 'fbe6da823c94a9a04623c4d683b00167',
			serial_number: null,
			sw_version: '3.2.3',
			via_device_id: null,
		},
	},
	areas: {
		bedroom: {
			aliases: [],
			area_id: 'bedroom',
			floor_id: 'second_floor',
			icon: 'mdi:bed-king',
			labels: [],
			name: 'Bedroom',
			picture: null,
			created_at: 0,
			modified_at: 0,
		},
		front_yard: {
			aliases: [],
			area_id: 'front_yard',
			floor_id: 'first_floor',
			icon: 'mdi:garage',
			labels: ['outside'],
			name: 'Front Yard',
			picture: null,
			created_at: 0,
			modified_at: 0,
		},
		kitchen: {
			aliases: [],
			area_id: 'kitchen',
			floor_id: 'first_floor',
			icon: 'mdi:countertop',
			labels: [],
			name: 'Kitchen',
			picture: null,
			created_at: 0,
			modified_at: 0,
		},
		lounge: {
			aliases: [],
			area_id: 'lounge',
			floor_id: 'first_floor',
			icon: 'mdi:sofa',
			labels: [],
			name: 'Lounge',
			picture: null,
			created_at: 0,
			modified_at: 0,
		},
	},
	floors: {
		first_floor: {
			aliases: ['Ground Floor'],
			created_at: 0,
			floor_id: 'first_floor',
			icon: null,
			level: 1,
			name: 'First Floor',
			modified_at: 0,
		},
		second_floor: {
			aliases: [],
			created_at: 0,
			floor_id: 'second_floor',
			icon: null,
			level: 2,
			name: 'Second Floor',
			modified_at: 0,
		},
	},
	connection: {
		async sendMessagePromise(request: { type: string }) {
			switch (request.type) {
				case 'config/label_registry/list':
					return [
						{
							color: 'yellow',
							created_at: 0,
							description: null,
							icon: 'm3s:light-group-rounded-filled',
							label_id: 'lighting',
							name: 'Lighting',
							modified_at: 0,
						},
						{
							color: 'light-green',
							created_at: 0,
							description: null,
							icon: 'mdi:ceiling-fan',
							label_id: 'lounge_ceiling_fan',
							name: 'Lounge Ceiling Fan',
							modified_at: 0,
						},
						{
							color: 'red',
							created_at: 0,
							description: null,
							icon: 'mdi:remote',
							label_id: 'ir',
							name: 'Infrared Remote',
							modified_at: 0,
						},
						{
							color: 'green',
							created_at: 0,
							description: null,
							icon: 'mdi:weather-sunny',
							label_id: 'outside',
							name: 'Outside',
							modified_at: 0,
						},
					];
				default:
					return [];
			}
		},
	},
	config: {
		unit_system: {
			length: 'mi',
		},
	},
} as unknown as HomeAssistant;
