name: Publish Package to npmjs
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Set git username
        run: git config --global user.name ${{ github.actor }}
      - name: Set git user email
        run: git config --global user.email "github-action-${{ github.actor }}.users.noreply.github.com"
      - name: Set package version to tag name
        run: npm version ${{ github.event.release.tag_name }}
      - name: Install dependencies and build
        run: npm ci
      - name: Publish package on npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
